### ISSUE TITLE
NoneType by Serfaus creation

### ISSUE THREAD

**Issue by javnik36** [javnik36/NextbikeOSM#20]
``` python
Traceback (most recent call last):
  File "nextbike_valid.py", line 189, in <module>
    c.pair(d)
  File "nextbike_valid.py", line 65, in pair
    for i in next_places:
TypeError: 'NoneType' object is not iterable
```

**Comment by javnik36** [comment]
It's working...let see on next generation

**Comment by javnik36** [comment]
wrong id by creation :facepunch:
